REDDIT_CLIENT_ID: str = "XXX"
REDDIT_CLIENT_SECRET: str = "XXX"
REDDIT_USER_AGENT: str = "XXX"
REDDIT_USERNAME: str = "XXX"
REDDIT_PASSWORD: str = "XXX"

TELEGRAM_TOKEN: str = "XXX"
TELEGRAM_CHAT_ID: int = 0
